### ISSUE TITLE
Boost b2 file installation is not getting completed nor throwing error(taking nearly a day but still not installed)

### ISSUE THREAD

**Issue by dhamodharankv09** [aws-samples/aws-iot-securetunneling-localproxy#102]
**Describe the bug**

**To Reproduce**

wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz -O /tmp/boost.tar.gz
tar xzvf /tmp/boost.tar.gz
cd boost_1_76_0
./bootstrap.sh
sudo ./b2 install link=static

**Expected behavior**

**Actual behavior**

A clear and concise description of what actually happened.

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferabbly, you can also [increase the verbosity](https://github.com/aws-samples/aws-iot-securetunneling-localproxy#options-set-via-command-line-arguments), for example to enable debug logs for the localproxy, you can use the cli option `-v 6`

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 16]
 - Architecture: [e.g. x86-64 or x86-32]
 - Localproxy commit: [e.g. [8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/commit/8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52)]

**Additional context**

**Comment by RogerZhongAWS** [comment]
Closing the issue as building boost from source requires > 1GB of memory. It is recommended to either using our ecr repo https://gallery.ecr.aws/aws-iot-securetunneling-localproxy or to build on a more powerful machine and copy the binary to your target device instead.
