### ISSUE TITLE
Raspberry PI 4  running Raspbian GNU/Linux 11 (bullseye) - atomic

### ISSUE THREAD

**Issue by seregicus** [aws-samples/aws-iot-securetunneling-localproxy#103]
[  4%] Linking CXX executable bin/localproxytest
/usr/bin/ld: /usr/local/lib/arm-linux-gnueabihf/libprotobuf-lite.a(arena.cc.o): in function `google::protobuf::internal::ThreadSafeArena::Init(bool)':
arena.cc:(.text+0xa60): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/localproxytest.dir/build.make:292: bin/localproxytest] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/localproxytest.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

It seems to be a problem linking to '__atomic_fetch_add_8' or the atomic libs? Any clues on how to resolve? Anyone been successful building this on an rPi?

**Comment by borner791** [comment]
I saw this same issue, it looks like moving 
`#libatomic ensured for all platforms except OSX and WINDOWS
if(NOT APPLE AND NOT MSVC)
    target_link_libraries(${AWS_TUNNEL_LOCAL_PROXY_TARGET_NAME} atomic)
    target_link_libraries(${AWS_TUNNEL_LOCAL_PROXY_TEST_NAME} atomic)
endif()
`
below 
`target_link_libraries(${AWS_TUNNEL_LOCAL_PROXY_TEST_NAME} ${Protobuf_LITE_STATIC_LIBRARY})` 

so basically to the end. This allows me to build on the Pi

**Comment by RogerZhongAWS** [comment]
Did not have time to validate this on raspberry pi yet, but yes this is an action item for the project.

**Comment by aikrana** [comment]
> I saw this same issue, it looks like moving `#libatomic ensured for all platforms except OSX and WINDOWS if(NOT APPLE AND NOT MSVC) target_link_libraries(${AWS_TUNNEL_LOCAL_PROXY_TARGET_NAME} atomic) target_link_libraries(${AWS_TUNNEL_LOCAL_PROXY_TEST_NAME} atomic) endif() ` below `target_link_libraries(${AWS_TUNNEL_LOCAL_PROXY_TEST_NAME} ${Protobuf_LITE_STATIC_LIBRARY})`
> 
> so basically to the end. This allows me to build on the Pi

Tried this and still having the same error (Raspberry 3B+). Any thoughts?

**Comment by nimysan** [comment]
i have tried this and resolved the issue.

`
sudo apt remove gcc
sudo apt install llvm
sudo apt install clang++
mkdir clangbuild
cmake -DCMAKE_EXE_LINKER_FLAGS="-latomic" ../
make
`

The key is using clang 11 instead of gcc and also add -DCMAKE_EXE_LINKER_FLAGS="-latomic"
