### ISSUE TITLE
exe file for arm32 

### ISSUE THREAD

**Issue by wildwindyevan** [aws-samples/aws-iot-securetunneling-localproxy#107]
could someone create one cross-compilation   for arm32?

**Comment by HarshGandhi-AWS** [comment]
Hello @wildwindyevan we have some [pre-built binaries](https://github.com/aws-samples/aws-iot-securetunneling-localproxy#using-pre-built-docker-images) created for local proxy. Can you use those? 

If not, then you can follow the steps mentioned[ over here](https://github.com/aws-samples/aws-iot-securetunneling-localproxy#using-pre-built-docker-images) for building a binary for your device requirements. 

Let us know if you still have any questions or need help in building binary.

**Comment by HarshGandhi-AWS** [comment]
Resolving this issue now. Please feel free to reopen this issue or create a new one if you have any further questions.
