### ISSUE TITLE
fails build with boost 1.81.0

### ISSUE THREAD

**Issue by thomas-roos** [aws-samples/aws-iot-securetunneling-localproxy#112]
**Describe the bug**

see error log
[builderror.log](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/10381765/builderror.log)

**To Reproduce**

build with yocto + meta-aws master branch 
(older boost release 1.80.0 work)

**Expected behavior**
build without errors

**Actual behavior**

see error log

**Comment by shangabl** [comment]
Hi Thomas,

We use boost 1.79 to build so we have not had this issue before... I will try to recreate with 1.81 and see what we can do.

**Comment by RogerZhongAWS** [comment]
boost is not always backward compatible, will need to review the areas that broke with the latest version.

**Comment by shangabl** [comment]
This may be a bug with boost 1.81 -- They do say this is a major update with some breaking changes but they do not mention anything about this. In fact, they say in 1.81 they added support for string_view...

https://www.boost.org/users/history/version_1_81_0.html

**Comment by thomas-roos** [comment]
Hi Shane,
would you like to report this bug if it is one.
What I found:
- here we are using boost beast
https://github.com/aws-samples/aws-iot-securetunneling-localproxy/blob/f5ae5d003d173ca3b3e25d1744c9536655088ba8/test/TestHttpServer.cpp#L13
- this here is talking about a similar problem:
https://github.com/boostorg/beast/issues/2594
Might you find a solution there - 
like they did here: https://github.com/LibreELEC/LibreELEC.tv/pull/7267/commits/4674e30878f75aa600f510cdc24fa6993454d3fd
I can not dive deep into this problem.

**Comment by shangabl** [comment]
Hi Thomas,

So, from that issue it looks like string_view.to_string() is actually deprecated.
`
BOOST_BEAST_USE_STD_STRING_VIEW is deprecated`

So, I think we will need to make some changes in order to be compatible with boost 1.81.

**Comment by shangabl** [comment]
I fixed this issue but then there was another breaking change and another...

Fixed 3/x so far... I think we will need to backlog this for now and recommend using 1.80 or older to build.

**Comment by thomas-roos** [comment]
ok, how long will it be backlogged then?
Next release of yocto will include boost 1.81 - by now it's only on their dev branch...

**Comment by shangabl** [comment]
I will discuss with the team today.

So, the next release of yocto including boost 1.81 will then be a blocker?

Do you know when that will be?

**Comment by thomas-roos** [comment]
imho it should be fixed soon - bad customer experience - no trust if this is supported in the future (roadmap changes) etc.
Mickledore release 4.2 is April 2023

**Comment by shangabl** [comment]
Agreed. I'll work on this in the near future. Does your team need this any earlier than the Mickledore 4.2 release? Just want to make sure we know our real deadline even though I plan to work on it soon.

**Comment by thomas-roos** [comment]
I don't know the exact date of Mickledore release, so lets say release 1. April. They do release candidate builds etc.
I think it should be finised by 1. March to get it ready...

**Comment by shangabl** [comment]
Merged!

**Comment by thomas-roos** [comment]
TY
