### ISSUE TITLE
Protobuf instructions - build is a file not a directory

### ISSUE THREAD

**Issue by monelgordillo** [aws-samples/aws-iot-securetunneling-localproxy#121]
**Describe the bug**

These instructions do not work.  build is a file.

```
3. Download and install Protobuf dependency
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protobuf-all-3.17.3.tar.gz -O /tmp/protobuf-all-3.17.3.tar.gz
tar xzvf /tmp/protobuf-all-3.17.3.tar.gz
cd protobuf-3.17.3
**mkdir build**
cd build
cmake ../cmake
make
sudo make install
```

**Comment by shangabl** [comment]
Hi @monelgordillo,

So, when you attempted to run mkdir build it said a file named build already exists? protobuf-3.17.3 should be a brand new directory so I am not sure how that would happen. The name of the directory 'build' is actually not important but nonetheless I do not think there should be a filed named build there already. You could make a directory with an arbitrary name though. Like build-monelgordillo then cd build-monelgordillo instead of build.

Can you get any information on the file 'build' in your protobuf-3.17.3 directory? Maybe I can help figure out why it is there.

**Comment by monelgordillo** [comment]
Howdy

The build file starts of like this:

`cat build                           
# Bazel (https://bazel.build/) BUILD file for Protobuf.

load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test", "objc_library", native_cc_proto_library = "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_lang_toolchain", "proto_library")
load("@rules_python//python:defs.bzl", "py_library")
load("@rules_java//java:defs.bzl", "java_binary", "java_proto_library", "java_lite_proto_library")
load(":cc_proto_blacklist_test.bzl", "cc_proto_blacklist_test")

licenses(["notice"])

exports_files(["LICENSE"])

################################################################################
# build configuration
################################################################################

################################################################################
# ZLIB configuration
################################################################################

ZLIB_DEPS = ["@zlib//:zlib"]

################################################################################
# Protobuf Runtime Library
################################################################################
`

**Comment by shangabl** [comment]
Hi Monica,

So, it looks like you're using Bazel to build which we do not support.

**Comment by monelgordillo** [comment]
Looks like I only get build as a file when I try to build from source on mac.  On Ubuntu, I don't get that.

**Comment by monelgordillo** [comment]
There's a file called BUILD - and mac isn't case sensitive. mac sees BUILD and build as the same thing.

**Comment by shangabl** [comment]
I am honestly not very familiar with Bazel but it does appear that a Bazel build file is causing this issue.
