### ISSUE TITLE
sudo apt install zlibc

### ISSUE THREAD

**Issue by ychamare** [aws-samples/aws-iot-securetunneling-localproxy#129]
**Describe the bug**

Ubunut : sudo apt install zlibc    - Does not exist 

**To Reproduce**

run command on ubuntu 

**Expected behavior**

**Actual behavior**

A clear and concise description of what actually happened.

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferabbly, you can also [increase the verbosity](https://github.com/aws-samples/aws-iot-securetunneling-localproxy#options-set-via-command-line-arguments), for example to enable debug logs for the localproxy, you can use the cli option `-v 6`

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 16]
 - Architecture: [e.g. x86-64 or x86-32]
 - Localproxy commit: [e.g. [8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/commit/8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52)]

**Additional context**

**Comment by HarshGandhi-AWS** [comment]
I have updated the instructions in documentation for installing `zlib` lib on Ubuntu device
