### ISSUE TITLE
Errors in building localproxy on Windows

### ISSUE THREAD

**Issue by harikiran27** [aws-samples/aws-iot-securetunneling-localproxy#133]
**Describe the bug**

Unable to build localproxy on Windows 10. Getting **LNK2019** and **LNK2001** errors when I run the final msbuild command.

**To Reproduce**

1. install zlib, protobuf (3.17), catch2 and openssl (1.1.1u) as per the documentation
2. install boost(1.81.0) using `.\b2 toolset=msvc address-model=64 install define=BOOST_WINAPI_VERSION_WIN10`
3. run `cmake -DWIN32_WINNT=0x0A00 -DBoost_USE_STATIC_LIBS=ON -DCMAKE_PREFIX_PATH="C:\Boost;C:\Program Files (x86)\Catch2;C:\Program Files (x86)\protobuf;C:\Program Files\OpenSSL" -G "Visual Studio 16 2019" -A x64 ..\` in aws-iot-securetunneling-localproxy\build folder
4. run `msbuild localproxy.vcxproj -p:Configuration=Release`

**Expected behavior**

Expected successful localproxy build

**Actual behavior**

Encountered LNK2019 and LNK2001 errors

**Logs**
console output of step 3 : 
![image](https://user-images.githubusercontent.com/59359722/233584900-ec19dd00-9905-47a2-abce-8ee97d6328ea.png)

console output of step 4: [msbuildlog.txt](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/11293687/msbuildlog.txt)

**Environment (please complete the following information):**
 - OS: Windows
 - Version 10
 - Architecture: x86-64
 - Localproxy commit: b6c31b442fa6d4c930e705d2853efd73dadff169
 - Using Visual Studio 2019

**Additional context**

I also tried using `-DWIN32_WINNT=_WIN32_WINNT_WIN10`, but got more errors alongwith **LNK2038**. 

Any help is appreciated.

**Comment by HarshGandhi-AWS** [comment]
Hello @harikiran27 , thank you for reaching out to us with this issue. Please be patient with us until we reproduce this issue and resolve the bug if present. 
To unblock yourself for now, I would suggest you to running local proxy on docker. Here is the [list of few container images](https://github.com/aws-samples/aws-iot-securetunneling-localproxy#using-pre-built-docker-images) which you can use. 

-Harsh Gandhi

**Comment by joe-ng-eguana** [comment]
Hi @HarshGandhi-AWS, I am running into the same problem when trying to build localproxy for Windows. Can the AWS team replicate this bug?

**Comment by arunsabat** [comment]
i am also struck with latest localproxy with boost 1.81 in windows build.  Can AWS team quickly look into it?

**Comment by gerbit** [comment]
Any progress on this one?

**Comment by abeytr** [comment]
I am also facing build errors while compiling localproxy in a windows OS with Boost 1.81. Request you to look into this asap.
I have attached the console output that describes the build errors.
[localProxy-WindowsBuild.txt](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/13052978/localProxy-WindowsBuild.txt)

**Comment by RogerZhongAWS** [comment]
Hey folks, I have tried building every boost library since 1.76 and found that from 1.77 to 1.78, there was a regression in the boost.log library which means we have to set  _WIN32_WINNT macro to windows 7 (0x0601) and the BOOST_USE_WINAPI_VERSION macro to windows 7

More details about the issue can be found in this thread here: https://github.com/microsoft/vcpkg/issues/22495

To fix, please reference the changes in this PR https://github.com/aws-samples/aws-iot-securetunneling-localproxy/pull/144 and rebuild. If you do not want to build from source, unofficial binaries produced by the github workflow can be downloaded with boost statically linked. You will still need OpenSSL as a shared library.
