### ISSUE TITLE
boost 1.84 format include missing

### ISSUE THREAD

**Issue by thomas-roos** [aws-samples/aws-iot-securetunneling-localproxy#148]
[boost-include-format.txt](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/14557133/boost-include-format.txt)

**Comment by thomas-roos** [comment]
Hi Harsh,
the file is a patch
+#include <boost/format.hpp>
is missing in /src/config/ConfigFile.cpp

**Comment by RogerZhongAWS** [comment]
patch has been incorporated into source in the above commit.
