### ISSUE TITLE
I tried to compile Localproxy but found that the underlying system supported is Debian12. Can I ask if Debian10 is supported or if there is a list of dependent package versions to help me install Localproxy

### ISSUE THREAD

**Issue by miss-creater** [aws-samples/aws-iot-securetunneling-localproxy#155]
I tried to compile Localproxy but found that the underlying system supported is Debian12. Can I ask if Debian10 is supported or if there is a list of dependent package versions to help me install Localproxy

**Comment by RogerZhongAWS** [comment]
I am not familiar with the behavior of running Debian 12 images on Debian 10. Do we know exactly what kind of issue you were encountering? Was the Docker container even able to start up or was there some compilation failure that happened down the line?

You can also try running the localproxy directly from the binary image without having to compile [aws-iot-securetunneling-localproxy/debian-bin](https://gallery.ecr.aws/aws-iot-securetunneling-localproxy/debian-bin)

But if all else fails, I suggest you modify the Dockerfile yourself and change the OS. Some dependent packages installed with apt on Deb 12 may need to be installed from source if the correct version is not available on apt.

**Comment by RogerZhongAWS** [comment]
closing issue, suggested workaround should be feasible
