### ISSUE TITLE
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake

### ISSUE THREAD

**Issue by martysweet** [aws-samples/aws-iot-securetunneling-localproxy#17]
While following the installation README I encountered the following errors while running `cmake ../` for the `aws-iot-securetunneling-localproxy` repo.

```bash
CMake Error at CMakeLists.txt:48 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106900
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:71 (find_package)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106900
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:71 (find_package)
...
...
```

I was using cmake version 3.5.1, on Ubuntu 16.04.4 LTS.

After upgrading to cmake version 3.16.4, following these steps https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu, the build was successful.

Should the required cmake version on the README.md page be higher than the stated 3.2?

Hope this helps anyone else having issues! :+1:

**Comment by HarshGandhi-AWS** [comment]
Hello @martysweet ,

Thank you for your feedback. I have tested and found out this issue to be present for CMake 3.5 version. I have updated the README as well. Again thank you for bringing this issue to our attention. 

Best regards,
Harsh Gandhi
