### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by pthomas01** [aws-samples/aws-iot-securetunneling-localproxy#18]
Have the following issues:
(a) This only builds with Boost 1.68 or Boost 1.69 - not with the latest version of boost.
(b) This does not build on Mac OSX (which I think uses the clang compiler)

It would be realy nice if you could provide binaries for Linux, WIndows and OSX. For example, I created a linux binary that works on pretty much all modern distributions. Making prebuilt binaries for linux, OSX and windows binary would be super useful.

**Comment by mhojnik** [comment]
For anyone else also helplessly searching for RPI binaries, here they are; https://devopstar.com/2019/12/25/greengrass-secure-tunneling

**Comment by HarshGandhi-AWS** [comment]
Hello @pthomas01 ,
Thank you for your feedback. Although we are not planning on providing support to prebuilt binaries for now, but your suggestion is taken into consideration for future updates.

**Comment by ltagliamonte** [comment]
@HarshGandhi-AWS is there some documentation to build the proxy on OSX?
Thanks.

**Comment by KareemAliAWS** [comment]
@ltagliamonte The easiest way would be to use the docker image to build it, you could also check the CI script for OSX here

https://github.com/aws-samples/aws-iot-securetunneling-localproxy/blob/master/.github/workflows/ci.yml

which basically builds it for OSX as part of the CI validation.
