### ISSUE TITLE
Multiple simultaneous TCP connections

### ISSUE THREAD

**Issue by pashinov** [aws-samples/aws-iot-securetunneling-localproxy#22]
Hello. If I understand properly the current version of IoT Security Tunneling implementation supports only one TCP connection at a time. Can you tell me is it possible to use your tunnel for multiple simultaneous TCP connections?

**Comment by HarshGandhi-AWS** [comment]
Hello Alexey,

Currently we do not support opening multiple connections at a time. Once it is available for use, either me or someone else from the team will update you here.

Thank you,
Harsh Gandhi

**Comment by pashinov** [comment]
So are you going to support it? If it is so can you tell me when you are roughly planning to release it?

**Comment by HarshGandhi-AWS** [comment]
Hello @pashinov ,

Thank-you for your feedback, this feature has been requested by many of our customers, and that will be a strong influence on the prioritization of this feature. However, at this time we cannot provide a date for this feature

Thank you,
Harsh Gandhi

**Comment by pashinov** [comment]
@HarshGandhi-AWS, Thanks for reply!

**Comment by HarshGandhi-AWS** [comment]
Closing this issue now, will post update once the feature is launched.
