### ISSUE TITLE
Costs

### ISSUE THREAD

**Issue by js1972** [aws-samples/aws-iot-securetunneling-localproxy#28]
$6 every time you create a tunnel ! Seriously...

There needs to be a certain number of tunnels free every month. As a developer trying to use this functionality you need to repeatedly open tunnels for test purposes - I copped a $60 bill for that. This is ludicrous. Development time should not be included.

What if I had a CI pipeline with my app - we'd cop $6 every time a test was run.

This is nice and handy software but rendered unusable due to costs...

**Comment by jrad36** [comment]
Hello ,
We’re sorry to hear you ran into issues while testing. Secure Tunneling is intended as a support tool used to troubleshoot high-value, remote devices. We plan on reaching out to you directly using the contact information on your website to learn about your use case and discuss options.

**Comment by RealHandy** [comment]
I have to second this. This doc: https://aws.amazon.com/iot-device-management/pricing/ references the usual fractions of cents for large volumes of other actions -- first 250,000 Remote Actions / Month is $0.003/action, for example or $3.00 per 1000 actions.

Then 1 tunnel to 1 device is $5.00. Huh? The first time someone inefficiently automates a device action through tunneling, they'll be very sorry.

Maybe, at the very least, shout from the rooftops in docs that tunneling is 1000x more expense than you think it is.

**Comment by TalKlinger** [comment]
@js1972 , Tunnels are a very powerful tool for one-offs. In case you have a process that requires more than once in a blue moon operation, I would recommend using IoT jobs (pulling logs, running package upgrades, OS upgrade).

**Comment by steffenstolze** [comment]
I just found this - **while scrolling through the issues**. This is mental.
We'll stop further development with that feature asap and use the EC2 SSH jumphost instead. $6 for opening a tunnel 👎
