### ISSUE TITLE
Feature request: stdin/stdout (a la socat) or unix domain socket bindings

### ISSUE THREAD

**Issue by sammck** [aws-samples/aws-iot-securetunneling-localproxy#3]
It would be more secure (access to listen port could be controlled), and avoid the problem of dynamically allocating available listen ports when potentially multiple instances of localproxy are running on the same host, if the local end of the proxy could be bound to either stdin/stdout or a unix domain socket, rather than a TCP socket. This is what socat does. If this feature existed, one could proxy SSH through localproxy without any local listen port; e.g.,

ssh -o "ProxyCommand localproxy -s  STDIO -t access-token" user@localhost

Ironically, on linux at least, STDIO binding is the *only* binding that is really needed to provide all types of connectivity including TCP and unix domain sockets, because STDIO can be piped through socat to any other transport type.

If it is interesting to you I would consider creating a pull request for STDIO support.

Thoughts?

**Comment by DavidOgunsAWS** [comment]
Sam,

Thanks for your feedback. This feature enables a more secure way to run the local proxy when it is known that application to connect to is local to a device or host.  We will consider this feature for future enhancement.

Thanks,
David O.

**Comment by HarshGandhi-AWS** [comment]
Hey Sam, 

Thank you for the suggestion. We will consider this feature for future enhancement.

Thanks,
Harsh G.
