### ISSUE TITLE
Boost 1.68/1.69 or 1.71?

### ISSUE THREAD

**Issue by TalKlinger** [aws-samples/aws-iot-securetunneling-localproxy#33]
When compiling from source, after completing successfully all the prequisits from the readme.
`cmake ../ `bumps an error, asking for boost 1.71.
After installing boost 1.71, the error seems to be resolved.
But when running `make` a header is deprecated in boost

> In file included from /usr/local/include/boost/config/header_deprecated.hpp:18,
                 from /usr/local/include/boost/pending/integer_log2.hpp:5,
                 from /usr/local/include/boost/random/detail/integer_log2.hpp:19,
                 from /usr/local/include/boost/random/detail/large_arithmetic.hpp:19,
                 from /usr/local/include/boost/random/detail/const_mod.hpp:23,
                 from /usr/local/include/boost/random/detail/seed_impl.hpp:26,
                 from /usr/local/include/boost/random/mersenne_twister.hpp:30,
                 from /usr/local/include/boost/uuid/random_generator.hpp:17,
                 from /usr/local/include/boost/uuid/uuid_generators.hpp:17,
                 from /home/tal/code/secure-tunnel/aws-iot-securetunneling-localproxy/test/TestWebsocketServer.cpp:10:
/usr/local/include/boost/pending/integer_log2.hpp:7:1: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
    7 | BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
      | ^~~~~~~~~~~~~~~~~~~~~~~
[ 53%] Linking CXX executable bin/localproxytest

I think there might be a mistake in the readme instructions

**Comment by KareemAliAWS** [comment]
1.69 should be fine, 1.7+ is not compatible, Could you share the full error log you got when you used 1.69?
