### ISSUE TITLE
catch2/catch.hpp not present

### ISSUE THREAD

**Issue by schleptech** [aws-samples/aws-iot-securetunneling-localproxy#36]
I am following these instructions at the request of an AWS support expert:
https://devopstar.com/2019/12/25/greengrass-secure-tunneling

I made it all the way to "make" under localproxy build, and am getting the following error. I consulted with my AWS engineer and he referred me to open an issue here. Here is my error:

`ubuntu@ubuntu:~/aws-iot-securetunneling-localproxy/build$ sudo make
[  6%] Building CXX object CMakeFiles/localproxytest.dir/test/AdapterTests.cpp.o
/home/ubuntu/aws-iot-securetunneling-localproxy/test/AdapterTests.cpp:4:10: fatal error: catch2/catch.hpp: No such file or directory
    4 | #include <catch2/catch.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/localproxytest.dir/build.make:71: CMakeFiles/localproxytest.dir/test/AdapterTests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/localproxytest.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

**Comment by KareemAliAWS** [comment]
The error indicate that it can't find a catch2 header file, that could mean that the lib wasn't installed or that you installed the wrong version of catch, Could you provide the full log and commands you ran?

**Comment by schleptech** [comment]
See below beginning with catch2 build

`ubuntu@ubuntu:~/protobuf-3.11.2/build$ cd
ubuntu@ubuntu:~$ sudo git clone https://github.com/catchorg/Catch2.git
Cloning into 'Catch2'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 30101 (delta 44), reused 48 (delta 23), pack-reused 29993
Receiving objects: 100% (30101/30101), 19.06 MiB | 675.00 KiB/s, done.
Resolving deltas: 100% (21148/21148), done.
ubuntu@ubuntu:~$ cd Catch2
ubuntu@ubuntu:~/Catch2$ sudo mkdir build
ubuntu@ubuntu:~/Catch2$ cd build
ubuntu@ubuntu:~/Catch2/build$ sudo cmake ..?
CMake Error: The source directory "/home/ubuntu/Catch2/build/..?" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
ubuntu@ubuntu:~/Catch2/build$ sudo cmake ../
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Catch2/build
ubuntu@ubuntu:~/Catch2/build$ sudo make
Scanning dependencies of target Catch2
[  1%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_automake.cpp.o
[  2%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_combined_tu.cpp.o
[  4%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_compact.cpp.o
[  5%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_console.cpp.o
[  7%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_cumulative_base.cpp.o
[  8%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_junit.cpp.o
[ 10%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_listening.cpp.o
[ 11%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_sonarqube.cpp.o
[ 13%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_streaming_base.cpp.o
[ 14%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_tap.cpp.o
[ 16%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_teamcity.cpp.o
[ 17%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/reporters/catch_reporter_xml.cpp.o
[ 19%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_approx.cpp.o
[ 20%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_assertion_handler.cpp.o
[ 22%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_assertion_result.cpp.o
[ 23%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/matchers/internal/catch_matchers_combined_tu.cpp.o
[ 25%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_clara.cpp.o
[ 26%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_commandline.cpp.o
[ 27%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_source_line_info.cpp.o
[ 29%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_config.cpp.o
[ 30%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_console_colour.cpp.o
[ 32%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_context.cpp.o
[ 33%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_debug_console.cpp.o
[ 35%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_debugger.cpp.o
[ 36%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_enforce.cpp.o
[ 38%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_enum_values_registry.cpp.o
[ 39%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_exception_translator_registry.cpp.o
[ 41%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_fatal_condition_handler.cpp.o
[ 42%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/generators/internal/catch_generators_combined_tu.cpp.o
[ 44%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/interfaces/catch_interfaces_combined_tu.cpp.o
[ 45%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/interfaces/catch_interfaces_reporter.cpp.o
[ 47%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_list.cpp.o
[ 48%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/matchers/catch_matchers_floating_point.cpp.o
[ 50%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/matchers/catch_matchers_string.cpp.o
[ 51%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/matchers/catch_matchers_templated.cpp.o
[ 52%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_message.cpp.o
[ 54%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_output_redirect.cpp.o
[ 55%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_registry_hub.cpp.o
[ 57%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_combined_tu.cpp.o
[ 58%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_random_number_generator.cpp.o
[ 60%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_reporter_registry.cpp.o
[ 61%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_result_type.cpp.o
[ 63%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_run_context.cpp.o
[ 64%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_section.cpp.o
[ 66%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_session.cpp.o
[ 67%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_singletons.cpp.o
[ 69%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_stream.cpp.o
[ 70%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_stringref.cpp.o
[ 72%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_string_manip.cpp.o
[ 73%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_tag_alias_registry.cpp.o
[ 75%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_test_case_info.cpp.o
[ 76%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_test_case_registry_impl.cpp.o
[ 77%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_test_case_tracker.cpp.o
[ 79%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_test_registry.cpp.o
[ 80%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_textflow.cpp.o
[ 82%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_test_spec.cpp.o
[ 83%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_test_spec_parser.cpp.o
[ 85%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_timer.cpp.o
[ 86%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_tostring.cpp.o
[ 88%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_totals.cpp.o
[ 89%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/catch_version.cpp.o
[ 91%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_wildcard_pattern.cpp.o
[ 92%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/internal/catch_xmlwriter.cpp.o
[ 94%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/benchmark/internal/catch_benchmark_combined_tu.cpp.o
[ 95%] Building CXX object src/CMakeFiles/Catch2.dir/catch2/benchmark/detail/catch_stats.cpp.o
[ 97%] Linking CXX static library libCatch2.a
[ 97%] Built target Catch2
Scanning dependencies of target Catch2WithMain
[ 98%] Building CXX object src/CMakeFiles/Catch2WithMain.dir/catch2/internal/catch_main.cpp.o
[100%] Linking CXX static library libCatch2Main.a
[100%] Built target Catch2WithMain
ubuntu@ubuntu:~/Catch2/build$ sudo make install
[ 97%] Built target Catch2
[100%] Built target Catch2WithMain
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/cmake/Catch2/Catch2Config.cmake
-- Installing: /usr/local/lib/cmake/Catch2/Catch2ConfigVersion.cmake
-- Installing: /usr/local/share/doc/Catch2
-- Installing: /usr/local/share/doc/Catch2/own-main.md
-- Installing: /usr/local/share/doc/Catch2/migrate-v2-to-v3.md
-- Installing: /usr/local/share/doc/Catch2/benchmarks.md
-- Installing: /usr/local/share/doc/Catch2/limitations.md
-- Installing: /usr/local/share/doc/Catch2/cmake-integration.md
-- Installing: /usr/local/share/doc/Catch2/test-fixtures.md
-- Installing: /usr/local/share/doc/Catch2/other-macros.md
-- Installing: /usr/local/share/doc/Catch2/why-catch.md
-- Installing: /usr/local/share/doc/Catch2/deprecations.md
-- Installing: /usr/local/share/doc/Catch2/ci-and-misc.md
-- Installing: /usr/local/share/doc/Catch2/logging.md
-- Installing: /usr/local/share/doc/Catch2/slow-compiles.md
-- Installing: /usr/local/share/doc/Catch2/generators.md
-- Installing: /usr/local/share/doc/Catch2/Readme.md
-- Installing: /usr/local/share/doc/Catch2/assertions.md
-- Installing: /usr/local/share/doc/Catch2/test-cases-and-sections.md
-- Installing: /usr/local/share/doc/Catch2/matchers.md
-- Installing: /usr/local/share/doc/Catch2/configuration.md
-- Installing: /usr/local/share/doc/Catch2/list-of-examples.md
-- Installing: /usr/local/share/doc/Catch2/release-notes.md
-- Installing: /usr/local/share/doc/Catch2/release-process.md
-- Installing: /usr/local/share/doc/Catch2/tutorial.md
-- Installing: /usr/local/share/doc/Catch2/event-listeners.md
-- Installing: /usr/local/share/doc/Catch2/reporters.md
-- Installing: /usr/local/share/doc/Catch2/opensource-users.md
-- Installing: /usr/local/share/doc/Catch2/command-line.md
-- Installing: /usr/local/share/doc/Catch2/contributing.md
-- Installing: /usr/local/share/doc/Catch2/commercial-users.md
-- Installing: /usr/local/share/doc/Catch2/tostring.md
-- Installing: /usr/local/lib/cmake/Catch2/ParseAndAddCatchTests.cmake
-- Installing: /usr/local/lib/cmake/Catch2/Catch.cmake
-- Installing: /usr/local/lib/cmake/Catch2/CatchAddTests.cmake
-- Installing: /usr/local/share/Catch2/gdbinit
-- Installing: /usr/local/share/Catch2/lldbinit
-- Installing: /usr/local/share/pkgconfig/catch2.pc
-- Installing: /usr/local/share/pkgconfig/catch2-with-main.pc
-- Installing: /usr/local/lib/libCatch2.a
-- Installing: /usr/local/lib/libCatch2Main.a
-- Installing: /usr/local/lib/cmake/Catch2/Catch2Targets.cmake
-- Installing: /usr/local/lib/cmake/Catch2/Catch2Targets-noconfig.cmake
-- Installing: /usr/local/include/catch2
-- Installing: /usr/local/include/catch2/catch_message.hpp
-- Installing: /usr/local/include/catch2/interfaces
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_capture.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_reporter.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_generatortracker.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_reporter_factory.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_runner.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_tag_alias_registry.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_all.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_testcase.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_registry_hub.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_exception.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_reporter_registry.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_enum_values_registry.hpp
-- Installing: /usr/local/include/catch2/interfaces/catch_interfaces_config.hpp
-- Installing: /usr/local/include/catch2/catch_approx.hpp
-- Installing: /usr/local/include/catch2/catch_session.hpp
-- Installing: /usr/local/include/catch2/catch_section_info.hpp
-- Installing: /usr/local/include/catch2/generators
-- Installing: /usr/local/include/catch2/generators/catch_generators_range.hpp
-- Installing: /usr/local/include/catch2/generators/catch_generators_random.hpp
-- Installing: /usr/local/include/catch2/generators/catch_generator_exception.hpp
-- Installing: /usr/local/include/catch2/generators/catch_generators_all.hpp
-- Installing: /usr/local/include/catch2/generators/catch_generators.hpp
-- Installing: /usr/local/include/catch2/generators/catch_generators_adapters.hpp
-- Installing: /usr/local/include/catch2/generators/internal
-- Installing: /usr/local/include/catch2/catch_tag_alias_autoregistrar.hpp
-- Installing: /usr/local/include/catch2/catch_config.hpp
-- Installing: /usr/local/include/catch2/benchmark
-- Installing: /usr/local/include/catch2/benchmark/detail
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_complete_invoke.hpp
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_repeat.hpp
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_estimate_clock.hpp
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_analyse.hpp
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_measure.hpp
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_timing.hpp
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_stats.hpp
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_benchmark_function.hpp
-- Installing: /usr/local/include/catch2/benchmark/detail/catch_run_for_at_least.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_sample_analysis.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_environment.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_outlier_classification.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_chronometer.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_optimizer.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_estimate.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_benchmark_all.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_clock.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_execution_plan.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_constructor.hpp
-- Installing: /usr/local/include/catch2/benchmark/catch_benchmark.hpp
-- Installing: /usr/local/include/catch2/benchmark/internal
-- Installing: /usr/local/include/catch2/catch_template_test_macros.hpp
-- Installing: /usr/local/include/catch2/catch_tag_alias.hpp
-- Installing: /usr/local/include/catch2/reporters
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_cumulative_base.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_teamcity.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_helpers.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_console.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_sonarqube.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_junit.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_streaming_base.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporters_all.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_listening.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_event_listener.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_tap.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_automake.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_xml.hpp
-- Installing: /usr/local/include/catch2/reporters/catch_reporter_compact.hpp
-- Installing: /usr/local/include/catch2/matchers
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_contains.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_container_properties.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_predicate.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_quantifiers.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_all.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_exception.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_templated.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_vector.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_string.hpp
-- Installing: /usr/local/include/catch2/matchers/catch_matchers_floating_point.hpp
-- Installing: /usr/local/include/catch2/matchers/internal
-- Installing: /usr/local/include/catch2/matchers/internal/catch_matchers_impl.hpp
-- Installing: /usr/local/include/catch2/catch_timer.hpp
-- Installing: /usr/local/include/catch2/catch_version.hpp
-- Installing: /usr/local/include/catch2/catch_tostring.hpp
-- Installing: /usr/local/include/catch2/catch_translate_exception.hpp
-- Installing: /usr/local/include/catch2/catch_version_macros.hpp
-- Installing: /usr/local/include/catch2/catch_totals.hpp
-- Installing: /usr/local/include/catch2/catch_test_case_info.hpp
-- Installing: /usr/local/include/catch2/catch_assertion_info.hpp
-- Installing: /usr/local/include/catch2/catch_reporter_registrars.hpp
-- Installing: /usr/local/include/catch2/catch_test_spec.hpp
-- Installing: /usr/local/include/catch2/catch_test_macros.hpp
-- Installing: /usr/local/include/catch2/catch_all.hpp
-- Installing: /usr/local/include/catch2/catch_assertion_result.hpp
-- Installing: /usr/local/include/catch2/internal
-- Installing: /usr/local/include/catch2/internal/catch_stream.hpp
-- Installing: /usr/local/include/catch2/internal/catch_source_line_info.hpp
-- Installing: /usr/local/include/catch2/internal/catch_windows_h_proxy.hpp
-- Installing: /usr/local/include/catch2/internal/catch_meta.hpp
-- Installing: /usr/local/include/catch2/internal/catch_case_sensitive.hpp
-- Installing: /usr/local/include/catch2/internal/catch_test_registry.hpp
-- Installing: /usr/local/include/catch2/internal/catch_noncopyable.hpp
-- Installing: /usr/local/include/catch2/internal/catch_clara.hpp
-- Installing: /usr/local/include/catch2/internal/catch_decomposer.hpp
-- Installing: /usr/local/include/catch2/internal/catch_context.hpp
-- Installing: /usr/local/include/catch2/internal/catch_uncaught_exceptions.hpp
-- Installing: /usr/local/include/catch2/internal/catch_compiler_capabilities.hpp
-- Installing: /usr/local/include/catch2/internal/catch_output_redirect.hpp
-- Installing: /usr/local/include/catch2/internal/catch_result_type.hpp
-- Installing: /usr/local/include/catch2/internal/catch_reporter_registry.hpp
-- Installing: /usr/local/include/catch2/internal/catch_config_android_logwrite.hpp
-- Installing: /usr/local/include/catch2/internal/catch_to_string.hpp
-- Installing: /usr/local/include/catch2/internal/catch_platform.hpp
-- Installing: /usr/local/include/catch2/internal/catch_assertion_handler.hpp
-- Installing: /usr/local/include/catch2/internal/catch_test_failure_exception.hpp
-- Installing: /usr/local/include/catch2/internal/catch_config_wchar.hpp
-- Installing: /usr/local/include/catch2/internal/catch_errno_guard.hpp
-- Installing: /usr/local/include/catch2/internal/catch_polyfills.hpp
-- Installing: /usr/local/include/catch2/internal/catch_test_case_tracker.hpp
-- Installing: /usr/local/include/catch2/internal/catch_debug_console.hpp
-- Installing: /usr/local/include/catch2/internal/catch_test_spec_parser.hpp
-- Installing: /usr/local/include/catch2/internal/catch_option.hpp
-- Installing: /usr/local/include/catch2/internal/catch_wildcard_pattern.hpp
-- Installing: /usr/local/include/catch2/internal/catch_section.hpp
-- Installing: /usr/local/include/catch2/internal/catch_random_number_generator.hpp
-- Installing: /usr/local/include/catch2/internal/catch_debugger.hpp
-- Installing: /usr/local/include/catch2/internal/catch_singletons.hpp
-- Installing: /usr/local/include/catch2/internal/catch_stringref.hpp
-- Installing: /usr/local/include/catch2/internal/catch_enum_values_registry.hpp
-- Installing: /usr/local/include/catch2/internal/catch_leak_detector.hpp
-- Installing: /usr/local/include/catch2/internal/catch_container_nonmembers.hpp
-- Installing: /usr/local/include/catch2/internal/catch_stream_end_stop.hpp
-- Installing: /usr/local/include/catch2/internal/catch_config_uncaught_exceptions.hpp
-- Installing: /usr/local/include/catch2/internal/catch_startup_exception_registry.hpp
-- Installing: /usr/local/include/catch2/internal/catch_message_info.hpp
-- Installing: /usr/local/include/catch2/internal/catch_preprocessor.hpp
-- Installing: /usr/local/include/catch2/internal/catch_exception_translator_registry.hpp
-- Installing: /usr/local/include/catch2/internal/catch_config_counter.hpp
-- Installing: /usr/local/include/catch2/internal/catch_console_width.hpp
-- Installing: /usr/local/include/catch2/internal/catch_xmlwriter.hpp
-- Installing: /usr/local/include/catch2/internal/catch_unique_ptr.hpp
-- Installing: /usr/local/include/catch2/internal/catch_string_manip.hpp
-- Installing: /usr/local/include/catch2/internal/catch_list.hpp
-- Installing: /usr/local/include/catch2/internal/catch_fatal_condition_handler.hpp
-- Installing: /usr/local/include/catch2/internal/catch_enforce.hpp
-- Installing: /usr/local/include/catch2/internal/catch_run_context.hpp
-- Installing: /usr/local/include/catch2/internal/catch_textflow.hpp
-- Installing: /usr/local/include/catch2/internal/catch_template_test_registry.hpp
-- Installing: /usr/local/include/catch2/internal/catch_test_case_registry_impl.hpp
-- Installing: /usr/local/include/catch2/internal/catch_commandline.hpp
-- Installing: /usr/local/include/catch2/internal/catch_tag_alias_registry.hpp
-- Installing: /usr/local/include/catch2/internal/catch_lazy_expr.hpp
-- Installing: /usr/local/include/catch2/internal/catch_test_macro_impl.hpp
-- Installing: /usr/local/include/catch2/internal/catch_console_colour.hpp
ubuntu@ubuntu:~/Catch2/build$ cd
ubuntu@ubuntu:~$ sudo git clone https://github.com/aws-samples/aws-iot-securetunneling-localproxy
Cloning into 'aws-iot-securetunneling-localproxy'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 149 (delta 10), reused 32 (delta 9), pack-reused 103
Receiving objects: 100% (149/149), 142.09 KiB | 331.00 KiB/s, done.
Resolving deltas: 100% (57/57), done.
ubuntu@ubuntu:~$ cd aws-iot-securetunneling-localproxy
ubuntu@ubuntu:~/aws-iot-securetunneling-localproxy$ sudo mkdir build
ubuntu@ubuntu:~/aws-iot-securetunneling-localproxy$ cd build
ubuntu@ubuntu:~/aws-iot-securetunneling-localproxy/build$ sudo cmake ../ -DCMAKE_CXX_FLAGS=-latomic
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/local/lib/libprotobuf.a;-lpthread (found suitable version "3.11.2", minimum required is "3.6.1") 
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.1f")  
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.68.0") found components: system log log_setup thread program_options date_time filesystem 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/aws-iot-securetunneling-localproxy/build
ubuntu@ubuntu:~/aws-iot-securetunneling-localproxy/build$ sudo make
[  6%] Running cpp protocol buffer compiler on /home/ubuntu/aws-iot-securetunneling-localproxy/resources/Message.proto
Scanning dependencies of target localproxytest
[ 13%] Building CXX object CMakeFiles/localproxytest.dir/test/AdapterTests.cpp.o
/home/ubuntu/aws-iot-securetunneling-localproxy/test/AdapterTests.cpp:4:10: fatal error: catch2/catch.hpp: No such file or directory
    4 | #include <catch2/catch.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/localproxytest.dir/build.make:71: CMakeFiles/localproxytest.dir/test/AdapterTests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/localproxytest.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by schleptech** [comment]
Here's a txt file - it might be easier to read
[localproxy_build_error.txt](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/5753184/localproxy_build_error.txt)

**Comment by KareemAliAWS** [comment]
When you run `sudo git clone https://github.com/catchorg/Catch2.git`, git will checked the develop branch of catch2 which breaks backwards compatibility, Try removing the installed library and re- install it using `git clone --branch v2.13.2 https://github.com/catchorg/Catch2.git` as per the instruction in the README.md

**Comment by schleptech** [comment]
That seemed to have worked. However, I am now getting a different error:
`TcpAdapterProxy.cpp:(.text+0x89fc): undefined reference to `boost::log::v2_mt_posix::aux::unhandled_exception_count()'`
Txt file attached
[boost_error.txt](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/5755009/boost_error.txt)

**Comment by KareemAliAWS** [comment]
@schleptech You're using the wrong version of boost, please check the README.md file for the version of the dependencies.

**Comment by schleptech** [comment]
I just read readme - rebuilt boost per Readme to 1.69. 
Still getting same error. Attached is txt

Also boost ls:
`ubuntu@ubuntu:~/boost_1_69_0$ ls
INSTALL  LICENSE_1_0.txt  bin.v2  boost            boost.css  boostcpp.jam   bootstrap.log  doc        index.html  more                project-config.jam.1  rst.css  tools
Jamroot  b2               bjam    boost-build.jam  boost.png  bootstrap.bat  bootstrap.sh   index.htm  libs        project-config.jam  project-config.jam.2  status
[boosterror2.txt](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/5755263/boosterror2.txt)
`

**Comment by KareemAliAWS** [comment]
@schleptech You'll need to re-run cmake as well and point it to the right boost dependency since you have multiple versions installed

**Comment by schleptech** [comment]
I did what you said above - I then spent most of the afternoon re-building everything. The boost version is correct - 1.7 I believe. I am still getting boost issues. See attached txt. Please advise
[boost_error3.txt](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/5756062/boost_error3.txt)

**Comment by KareemAliAWS** [comment]
@schleptech 1.7 is not correct, it broke backwards compatibility. It has to be 1.68 or 1.69. so you need to remove all boost versions, make sure you only have 1.68 or 1.69, and then proceed.

https://github.com/aws-samples/aws-iot-securetunneling-localproxy#prerequisites-1
https://github.com/aws-samples/aws-iot-securetunneling-localproxy#2-download-and-install-boost-dependency
