### ISSUE TITLE
IoT Secure Tunneling boost library 

### ISSUE THREAD

**Issue by AlexCatlan** [aws-samples/aws-iot-securetunneling-localproxy#39]
We've tried to build a windows local proxy to get access to a device through the AWS IoT Core using these instructions but I have a issue on how to build the boost library (1.68). I've succeeded with installing version 1.75 but the current version of local proxy is using function calls which are no longer support in 1.68. Below I've attached a print screen of the boost library error I receive.
![BoostLibraryCMD](https://user-images.githubusercontent.com/72912226/111468571-605ec100-872e-11eb-8a91-7366d321ab6c.png)

**Comment by KareemAliAWS** [comment]
For the windows itself and visual studio, could you provide the version you're using and whether it's 32-bit or 64-bit?

And could you provide the the full commands you ran their full output as well?

**Comment by AlexCatlan** [comment]
Hello Kareem,

The version of Windows and Visual Studio is 64-bit and I've attached the full output here. 
[bootstrap.log](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/6163237/bootstrap.log)
[b2.log](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/6163238/b2.log)
[logalproxy.log](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/6163239/logalproxy.log)

**Comment by KareemAliAWS** [comment]
Thanks Alex, Could you also share the full commands you ran and which Visual Studio (like 2013? 2017?) and which version of windows are you using (windows 10? windows 8?)? I see the log files only contains the outputs.

**Comment by KareemAliAWS** [comment]
Thanks Alex

I see from the `logalproxy.log` file that you're also using `Windows 10`, `Visual Studio 2019`, is that correct? I see a problem with the command for building the localproxy but let's focus on boost first, Could you also share the command you ran to install boost? I don't see it in the `b2.log` file. It starts with 
```
warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.
```
which makes me suspect it's Visual Studio issue a similar to the one mentioned [here](https://github.com/microsoft/vcpkg/issues/5302#issuecomment-460876996)

**Comment by AlexCatlan** [comment]
Hi Kareem,

Thank you for the guidance, really helpful. We managed to build boost by changing from VS150 to VS160 in msvc.jam . 
[msbuild_log.txt](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/files/6170023/msbuild_log.txt)

**Comment by KareemAliAWS** [comment]
nice! 

Could you share the following the full cmake command you ran and its output as well?

**Comment by AlexCatlan** [comment]
Hi Kareem,

Great news  ! We deleted the CMake files created in the build directory to run CMake again and send you it's output and this time the project compiled without any errors. Thank you very much for your help.

**Comment by KareemAliAWS** [comment]
@AlexCatlan You're welcome!
