### ISSUE TITLE
does not work over network proxy. 

### ISSUE THREAD

**Issue by arunsabat** [aws-samples/aws-iot-securetunneling-localproxy#4]
The application does not work in proxy. Can you please provide support for proxy?

**Comment by DavidOgunsAWS** [comment]
Hi Arun,

Can you be more specific about what cannot be accomplished that you're trying to do? If you're seeing errors or run time issues that need troubleshooting, use the AWS Forums or contact AWS Support.

Thanks,
David Oguns

**Comment by arunsabat** [comment]
Sorry that I was not clear. The "proxy" i meant was network proxy. E.g if the device is behind the network proxy, how can I specify the proxy ip address and port? 
currently if i am running the localproxy application, i am getting following error.

[2019-12-14T00:14:14.154720]{28044}[info]    Attempting to establish web socket connection with endpoint wss://data.tunneling.iot.eu-west-1.amazonaws.com:443
[2019-12-14T00:14:35.682200]{28044}[error]   Could not connect to proxy server: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by DavidOgunsAWS** [comment]
Arun,

Thank you for clarifying your issue a bit. Just to be clear, this is network proxy that interprets the HTTP requests and forwards them? This sort of proxy currently is not supported in the local proxy reference implementation. We understand the utility of this and will look into adding the feature!

Thanks,
David Oguns

**Comment by DavidOgunsAWS** [comment]
Sorry about the edit on the prior reply. There are some need changes to the local proxy needed to support this feature. We will consider adding this for future improvement.

**Comment by arunsabat** [comment]
Thank You David for considering it for future improvement.

**Comment by pranaypratyush** [comment]
@DavidOgunsAWS thank you for your work. This type of configuration is pretty common in office and university public wifi/lan where u can only access the internet through a local HTTP proxy. So only ports 80 and 443 are open. So we can usually create an vpn server outside this network that accepts tcp connections on port 433 (like openvpn) and tunnel through the proxy over to the vpn server to access the internet without restrictions. But obviously that's not a good solution, and quite likely to be frowned upon by the management :-P

**Comment by HarshGandhi-AWS** [comment]
Hello Arun,
Hello  Pranay, 

Thank you for suggesting us this feature. As David mentioned, we were not considering network proxies while working on this project but we have your feature request under consideration for future enhancement. 

Thank you,
Harsh Gandhi
