### ISSUE TITLE
Cannot fully proxy socket connection due to inability to shut down send side separately from receive side

### ISSUE THREAD

**Issue by sammck** [aws-samples/aws-iot-securetunneling-localproxy#5]
Many protocols depend on independent shutdown of the send and receive sides of a socket connection (via the shutdown() posix API; see https://linux.die.net/man/3/shutdown). In particular, for HTTP 1.0 POST requests (or any HTTP 1.0 requests with variable-size payload), the server can only determine the end of the POSTed data by reading until it reaches the end of stream (caused by the client shutting down its send side). The server then processes the request and sends the HTTP response before closing its send side -- the server's socket is not freed until its send side is drained. The client then reads the entire response until end of stream, before closing the entire socket.

It would be useful to have an additional Message.Type END_OF_DATA to indicate that the receiving localproxy should shutdown() its send side for its local connection. Similarly, the sending local proxy should send END_OF_DATA to the cloud proxy service when it receives an end-of-stream indication while attempting to recv from its local connection.

**Comment by DavidOgunsAWS** [comment]
Sam,

Thanks for your feedback. This looks like a much needed feature we will consider adding. It cannot be added to the current WebSocket sub protocol version because if a new message type is sent, it has a meaning that cannot be safely ignored, and thus it would break compatibility any existing local proxy clients using the 'aws.iot.securetunneling-1.0' sub protocol.

**Comment by HarshGandhi-AWS** [comment]
Hello Sam,

Thank you for your feedback. As David mentioned in the above comment, to avoid any compatibility issue for any existing local proxy client we are not considering to add this feature to the current WebSocket sub protocol version but it is under consideration for future enhancement. 

Thanks, 
Harsh Gandhi
