### ISSUE TITLE
meta-aws support for this project removed

### ISSUE THREAD

**Issue by rpcme** [aws-samples/aws-iot-securetunneling-localproxy#51]
This is notification that Yocto Project support for this project has been removed from meta-aws due to lack of support for a sufficiently modern **boost** library.

When this issue has been resolved please file a ticket to this repo to include this project again.

https://github.com/aws/meta-aws

Thank you.

**Comment by kareali** [comment]
Thanks for the notification, I have checked the issue on `meta-aws` but it's not clear to me what is the problem with boost `1.69`, is there something more specific to this version that's causing a problem?

**Comment by rpcme** [comment]
Yocto Project core manages what gets shipped with the distribution and the mainline is currently at 1.76.  I am not sure exactly what the root cause is for the compilation failure.

If you would like to resolve - happy to work with you on the back channel.

**Comment by kareali** [comment]
@rpcme we've updated the repository to use the latest boost version, let me know if further updates are needed.
