### ISSUE TITLE
BUG - Docker image build failing due to download/install of boost

### ISSUE THREAD

**Issue by spitzzz** [aws-samples/aws-iot-securetunneling-localproxy#61]
**Describe the bug**

Download and install of boost is failing, causing the image build to fail

**To Reproduce**

Run the docker build script or build the image manually
```
./docker-build.sh
```

**Expected behavior**

Image built successfully.

**Actual behavior**

Build job fails with exit code:
```
executor failed running [/bin/sh -c wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz -O /tmp/boost.tar.gz && 	tar xzvf /tmp/boost.tar.gz && 	cd boost_1_76_0 && 	./bootstrap.sh && 	./b2 install && 	cd /home/dependencies]: exit code: 1
```

**Comment by kareali** [comment]
Discussed with @spitzzz and I still can't reproduce the problem on my mac, linux or windows machine.

**Comment by kareali** [comment]
Resolved after building boost with C++03 standard instead of the default (C++11) by adding `toolset=gcc cxxstd=03` to the bootstrap and build properties
```
./bootstrap toolset=gcc cxxstd=03
./b2 install toolset=gcc cxxstd=03
```
