### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by jongunter** [aws-samples/aws-iot-securetunneling-localproxy#67]
**Describe the bug**
Running `docker build` fails to complete.

**To Reproduce**

1. Download the repo
2. Run `./docker-build.sh`

**Expected behavior**
Docker build should succeed.

**Actual behavior**
Docker build fails. 

**Logs**
```
common.copy /usr/local/lib/libboost_graph.a
common.copy /usr/local/lib/cmake/boost_graph-1.76.0/libboost_graph-variant-static.cmake
...failed updating 9 targets...
...skipped 10 targets...
...updated 17051 targets...
The command '/bin/sh -c wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz -O /tmp/boost.tar.gz && 	tar xzvf /tmp/boost.tar.gz && 	cd boost_1_76_0 && 	./bootstrap.sh && 	./b2 install link=static && 	cd /home/dependencies' returned a non-zero code: 1
```

**Environment (please complete the following information):**
 - OS: OSX 10.15.7 
 - Architecture: x86
 - Localproxy commit: 6a06fef93f8db14f4945b2837a097f9f5a063799

**Comment by tkoki** [comment]
Hi @jongunter ,

I had same problem. It seems that boost build process stopped for some reaseon. (maybe insufficient memory)
I fixed this by increase Docker's Memory size to 6GB.

**Comment by juanoi** [comment]
I've also encountered a CMake-related issue while building on a Mac (Apple Silicon).

**To Reproduce**
- Checkout repo
- `./docker-build.sh`

**Logs**

```bash
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Protobuf: Found unsuitable version "3.6.1", but required is at least "3.17.3"
```

**Environment**
- OS: macOS Big Sur (11.6.1)
- Architecture: ARM 64 (Apple M1)
- Localproxy commit: `bc2f28`

**Comment by juanoi** [comment]
A follow up to my comment above.
This can be easily resolved by bumping up the protobuf version to 3.19. 
I ended up encountering another similar version-related error with Boost. 
The solution is again to bump up the version to 1.76.

**Comment by JMH-Jarbydev** [comment]
Same Issue Here,  ERROR [builder  6/13] RUN wget https://boostorg.jfrog.io/artifactor

`executor failed running [/bin/sh -c wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz -O /tmp/boost.tar.gz && 	tar xzvf /tmp/boost.tar.gz && 	cd boost_1_76_0 && 	./bootstrap.sh && 	./b2 install link=static && 	cd /home/dependencies]: exit code: 1
`

**Comment by kareali** [comment]
@jongunter Boost has failed to build for some reason, I would need to see the full logs from inside the docker image to get an idea of why it's failing, try attaching your shell to the docker image and building from inside the image so that you can see the full logs.

**Comment by kareali** [comment]
@juanoi The Dockerfile already installs Boost 1.76 and Protobuf 3.17, I'm curious why is make detecting protobuf 3.6.1? and which softwares did you update?

**Comment by dflatow** [comment]
I'm having the same issue and created a new issue here #82. @kareali any ideas? @JMH-Jarbydev did bumping protobuff version work for you or increasing memory? I'm going to try those steps as well

**Comment by dflatow** [comment]
> Hi @jongunter ,
> 
> I had same problem. It seems that boost build process stopped for some reason. (maybe insufficient memory) I fixed this by increase Docker's Memory size to 6GB.

Increasing docker memory to 6GB fixed this!
