### ISSUE TITLE
Known security vulnerabilities

### ISSUE THREAD

**Issue by volphy** [aws-samples/aws-iot-securetunneling-localproxy#68]
I have build a Docker image using `docker-build.sh` script.

Architecture: aarch64  (AWS EC2 t4g instance type)

Then I push the newly built Docker image to the AWS ECR and enabled scan for vulnerabilities.

The following vulnerabilties have been found:
<img width="393" alt="security_vulnerabilities" src="https://user-images.githubusercontent.com/14802070/146551264-bd6f115a-bb24-4b05-8335-fab5a101fd40.png">

Are there plans resolve them, at least the MEDIUM severity ones?

**Comment by kareali** [comment]
@volphy This repo is a sample code for the localproxy, and the docker script is just an example for building it using Docker with Ubuntu image, but we do not own or maintain Ubuntu or Docker security, so I would suggest that you reach out to Ubuntu maintainers or switch a different OS.

**Comment by kareali** [comment]
@volphy Unfortunately those CVEs are in ubuntu which we have no control over, but I have made an update to use AmazonLinux instead which won't have those CVEs.
