### ISSUE TITLE
Build for Raspberry Pi 3

### ISSUE THREAD

**Issue by volphy** [aws-samples/aws-iot-securetunneling-localproxy#69]
Is it possible to build a Docker image for the Raspberry Pi 3 (architecture: armv7l)?

I cannot see any OpenSSL configuration for ARM 32 (armv7l):
https://github.com/aws-samples/aws-iot-securetunneling-localproxy/blob/master/docker-build.sh

**Comment by kareali** [comment]
@volphy I have not tested it myself but the `linux-generic64` usually works for most Raspberry Pis, if those configurations don't work, you can try to update the configurations to `linux-armv4` and then feel free to create a PR for it.
