### ISSUE TITLE
Amazon Linux for Docker limits the docker cross builds for ARM

### ISSUE THREAD

**Issue by wdalmut** [aws-samples/aws-iot-securetunneling-localproxy#72]
Hi,

i compiled the secure tunneling proxy a couple of times using Docker BuildX for ARMv7 (Raspberry PI) https://hub.docker.com/repository/docker/wdalmut/aws-iot-localproxy and we are using it via Docker on Raspberries.

The choice to switch the Dockerfile from ubuntu:18.04 to Amazon Linux limits the build using buildx because it is not available for ARMv7 do you think that base image will be available for that architecture at some point? 

Do you think that is possible to switch back to Ubuntu instead?

**Comment by HarshGandhi-AWS** [comment]
Hello @wdalmut , 

Sorry for the delay in response. We are now looking into this issue. Will post updates over here once the issue is resolved. 

Regards,
Harsh Gandhi

**Comment by shangabl** [comment]
Hi wdalmut,

You could edit the Dockerfile to use ubuntu:18.04 and build again. We just do not use ubuntu as the default for our builds.

Shane
