### ISSUE TITLE
Support for new `client-token` header in local proxy

### ISSUE THREAD

**Issue by pedro-romano-zoi** [aws-samples/aws-iot-securetunneling-localproxy#85]
(Note: this is a follow up to #84. I'm from the same organization as @mayurpatelgec and AWS support recommended that we opened an issue here in the project after we've contacted them).

We've been successfully using the "AWS IoT Secure Tunneling Local Proxy Reference Implementation C++" executable, available through this project, to establish connections in both source and destination mode to AWS IoT Secure Tunnels.

Our implementation favors client access token reuse, since some of our things have unreliable internet connections that can drop frequently and need to be reestablished. It won't be practical in the short term to implement token rotation on the things so we would like to make use of the new client token functionality to enable client access token reuse.

[local proxy, doesn't currently support the client token](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/blob/eb951de124cabfc2f7d373407556896ac805c935/V2WebSocketProtocolGuide.md?plain=1#L45). Would it be possible to know if client token support will be added to local proxy in the near future?

**Comment by shangabl** [comment]
Support for client-token header has been merged!

Thank you.
