### ISSUE TITLE
[Feature request] scp supporting.

### ISSUE THREAD

**Issue by overheat** [aws-samples/aws-iot-securetunneling-localproxy#98]
I am wondering to know is it possibly support scp as ssh already works?

**Comment by RogerZhongAWS** [comment]
Hello, thanks for the question. Have you tried and are having issues using scp? It should work already if you want to do file transfers.

**Comment by shangabl** [comment]
SCP is supported. Resolving this issue.

Please feel free to open a new issue if you are having issues with SCP via Secure Tunneling.
